root: /home/viki/Documents/Erasmus/EEG-LM-alignment

defaults:
  - data: ubira
  - model: bert
  - vis: matplotlib
  - _self_

destpath: ./results/${path.datasets}

path:
  datasets: /home/viki/Documents/Erasmus/data_playground

# DataFrame with Pearson/Spearman correlations
save_folder: ${root}/results #/${path.datasets}
label_name: ${.data.labels[0]}_${.data.n_sentences}_sent
tab_name: correlations_${.data.labels[0]}_${.data.n_sentences}_sent.csv
tab_attrs: ['Channel', 'distance', 'truncate_start', 'truncate_end', 'pearson', 'spearman']

distance: cosine # cosine (l2, levenshtein-l2, levenshtein-cosine)