root: /home/viki/Documents/Erasmus/EEG-LM-alignment

defaults:
  - data: ubira
  - model: bert
  - _self_

destpath: ./results/${path.datasets}

path:
  datasets: /home/viki/Documents/Erasmus/data_playground

# DataFrame with Pearson/Spearman correlations
save_folder: ${root}/results #/${path.datasets}
tab_name: correlations_${.data.labels[0]}.csv #_${.data.n_sentences}_sent
tab_attrs: ['Channel', 'distance', 'truncate_start', 'truncate_end', 'pearson', 'spearman']


# Correlations RUN configuration
word_distance: levenshtein
pad_step: 4
timesteps: 5
